#!/usr/bin/env python
# coding: utf-8

# In[1]:


# Copyright (c) 2026 Hiroshi Harada
# Licensed under the MIT License.
# https://opensource.org/licenses/MIT
# Author: Hiroshi Harada
# Date: March 21, 2026

def get_odd_part(n):
    """
    Return the odd part of n by dividing out all factors of 2.
    This is essential for comparing the standard Collatz odd-sequence
    with the Shiftless Collatz odd-sequence.
    """
    if n == 0:
        return 0
    while n % 2 == 0:
        n //= 2
    return n


def verify_equivalence(seed):
    """
    Verify the mathematical identity between:

    1. Standard Collatz:
       The sequence of odd numbers generated by repeatedly applying
       (3n + 1) and removing all factors of 2.

    2. Shiftless Collatz:
       The sequence generated by n_{k+1} = 3n_k + LSB(n_k),
       where LSB(n) is the binary weight of the least significant bit (2^v).

    The odd part of the Shiftless trajectory must match the odd part
    of the standard Collatz trajectory at every step.
    """

    n_std = get_odd_part(seed)   # Standard Collatz odd part
    n_sft = seed                 # Shiftless Collatz full value
    step = 0

    print(f"Verification for Seed: {seed}")
    print(f"{'Step':<5} | {'Standard (Odd)':<15} | {'Shiftless':<25} | {'Odd(Shiftless)':<15} | Match?")
    print("-" * 90)

    # Continue until Shiftless Collatz reaches a power of 2 (Jackpot)
    while not (n_sft > 0 and ((n_sft & (n_sft - 1)) == 0)):

        # Standard Collatz odd-step
        n_std = get_odd_part(3 * n_std + 1)

        # Shiftless Collatz step: 3n + LSB
        lsb = n_sft & -n_sft
        n_sft = 3 * n_sft + lsb

        step += 1

        # Odd part of Shiftless value
        odd_sft = get_odd_part(n_sft)

        # Check equivalence
        match = (n_std == odd_sft)

        print(f"{step:<5} | {n_std:<15} | {n_sft:<25} | {odd_sft:<15} | {match}")

    print("-" * 90)
    print(f"Verification Successful. Total steps to Jackpot: {step}")
    print(f"Final Jackpot Value: 2^{n_sft.bit_length() - 1}")


if __name__ == "__main__":
    # Recommended seeds: 27 or 703 (long-range synchronization)
    verify_equivalence(27)


# In[ ]:




